### PR TITLE
OpenTelemetry spans for gRPC ext_authz calls

### PR DESCRIPTION
**Pull request by vinhph0906**
I have some updated code support issues: https://github.com/open-policy-agent/opa/issues/4290. 

Signed-off-by: vinhph0906 <vinhph0906@gmail.com>

### CODE REVIEW

**Comment by srenatus** [comment]
Thanks for continuing to work on this. It looks like we've got two things done in this PR:
1. wiring up the code for emitting spans from the gRPC server
2. updating OpenTelemetry to 1.11.

Do we need to do both at the same time? Also, if we update OTel, we should probably do it in OPA, too. 🤔

**Comment by vinhph0906** [comment]
Hmm. It seems to auto-upgrade when I get package `go.opentelemetry.io/contrib/instrumentation/google.golang.org/grpc/otelgrpc` with the latest version. So I have changed to v0.32.0 to use OpenTelemetry 1.7.0.

**Review by srenatus — APPROVED** [review]
Code looks good -- did you try it? Can you see spans for in-policy `http.send` calls that properly descend from the incoming gRPC CheckRequest?

**Comment by vinhph0906** [comment]
This is a screenshot of my test.  As you see, the span `1d8477eca1a3d735`  is `http.send`.
image

**Comment by srenatus** [comment]
Thanks! I've had another look at the PR that introduced OTel into OPA, and it had come with a selected few good test cases -- https://github.com/open-policy-agent/opa/pull/4029/files#diff-96e5568a29ac9c59d1cae97c506ba296448cd5d76c2abacc98db1b0770185c3d -- Do you think you could add one or two here, too, please?

**Comment by vinhph0906** [comment]
It seems will take a lot of workloads. So I will update later(maybe next week).

**Comment by ashutosh-narkar** [comment]
Closing for now. Feel free to re-open when you get a chance to test this.

**Comment by sidharthramesh** [comment]
Hey @vinhph0906 need any help with the tests?

**Comment by sidharthramesh** [comment]
@ashutosh-narkar I believe some of the e2e tests have been covered. Please suggest what should be worked upon.

**Comment by sidharthramesh** [comment]
Also @srenatus I believe this is the more recent PR than #353. Same question still stands — is this code useful? Or would this feature have to be implemented from scratch due to updates in core OPA?

**Comment by srenatus** [comment]
Skimmed the code, only found nitpicks. The changes done in OPA were done for this, so it should fit nicely.

**Comment by sidharthramesh** [comment]
Alright. So can we reopen this PR?
What should be worked on in order for this to get merged?

**Comment by srenatus** [comment]
Please open a new PR with this, but without any of the changes to vendor/. We can discuss the minor things there.

**Comment by srenatus** [comment]
@LavaToaster The changes required to OPA -- which had been done in `vendor/` here -- have since been integrated in the main branch of OPA.

**Comment by LavaToaster** [comment]
> @LavaToaster The changes required to OPA -- which had been done in `vendor/` here -- have since been integrated in the main branch of OPA. 

Not quite. OPA uses http not gRPC. So includes vendored pkgs for http requests.

**Comment by srenatus** [comment]
Ah there's a misunderstanding here. This wasn't about adding dependencies -- that's OK -- this was about changing the OPA sources in `vendor/github.com/open-policy-agent/opa/`. That's not OK.

**Comment by srenatus** [comment]
Looks like it no longer does that -- it, or some related PR, did at some point. Either way, if someone wants to pick this up, please go ahead.

**Comment by srenatus** [comment]
🔍 https://github.com/open-policy-agent/opa-envoy-plugin/pull/353/files#diff-5ad5fc18e1103c09aefcae98284d6cd9e5285226e1652a7343b4665f244ea539 this is what I was referring to

**Comment by vinhph0906** [comment]
Can I re-create PR #371 to finish this?

**Comment by srenatus** [comment]
Please do! 👏

**Pull request closed without merging**
