### PR TITLE
golang: 1.13.7 -> 1.15.2

### PR DESCRIPTION
**Pull request by srenatus**
Adapted tests to work with that golang version.

Also ran `go mod tidy`.

### CODE REVIEW

**Review by patrick-east — APPROVED** [review]

**Comment by ashutosh-narkar** [comment]
This looks good @srenatus ! Can you squash your commits and then we can merge.

**Comment by srenatus** [comment]
@ashutosh-narkar done! 😃

**Review by ashutosh-narkar — APPROVED** [review]

**Comment by srenatus** [comment]
Heh 😅 I kind of assumed we had done that on OPA already, too. Looks like we haven't. If noone beats me to it, I'll take care of that this week. 🤞

**Comment by srenatus** [comment]
⏩ https://github.com/open-policy-agent/opa/pull/2742

**Pull request merged**
