### PR TITLE
rename default branch to main

### PR DESCRIPTION
**Pull request by srenatus**
Follow-up tasks from renaming the default branch to main in github's settings.

### CODE REVIEW

**Review by anderseknert — APPROVED** [review]

**Comment by ashutosh-narkar** [comment]
Are the CI checks working as expected on your fork ? Also once we merge this, we'll have to update [step 1 of the Istio tutorial](https://www.openpolicyagent.org/docs/latest/envoy-tutorial-istio/#1-install-opa-envoy) on the OPA website.

**Comment by srenatus** [comment]
@ashutosh-narkar good idea. So far, it's looking good: https://github.com/srenatus/opa-istio-plugin/runs/2882410144?check_suite_focus=true#step:2:457

**Comment by srenatus** [comment]
> Also once we merge this, we'll have to update step 1 of the Istio tutorial on the OPA website.



Yup, for consistency. It seems like the old URL will stay intact, github takes care of that. At least that's what I believe from the fact that I can curl `https://raw.githubusercontent.com/open-policy-agent/opa/master/capabilities.json` although the master branch of OPA was renamed.

**Comment by srenatus** [comment]
⏩ https://github.com/open-policy-agent/opa/pull/3578

**Pull request merged**
