### PR TITLE
add b3singleheader injection

### PR DESCRIPTION
**Pull request by be-a-bee**
add b3singleheader injection
add test to assert propagation of b3 single and multi headers.

### CODE REVIEW

**Comment by be-a-bee** [comment]
@ashutosh-narkar , please review.

**Review by ashutosh-narkar — APPROVED** [review]
@be-a-bee thanks for looking into this.

**Comment by be-a-bee** [comment]
@ashutosh-narkar  , when can we expect the next release ?

**Comment by ashutosh-narkar** [comment]
We have a monthly release cycle. There will be a release end of the month.

**Comment by be-a-bee** [comment]
Thanks @ashutosh-narkar  . is there a way we can have a nightly build kind of thing so that we can consume these changes in our environment ? Or any other alternative ? Please advise.

**Comment by ashutosh-narkar** [comment]
You can use for example the `openpolicyagent/opa:0.61.0-envoy-3` image which should have your changes.  See this [job](https://github.com/open-policy-agent/opa-envoy-plugin/actions/runs/7877191231/job/21492848173) for details.

**Pull request merged**
